/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestaoqualidadeprojetos.sistema_de_conformidade_etica.view;

/**
 *
 * @author Gabriel
 */
public class CriarNovoProjetoView extends javax.swing.JFrame {

    /**
     * Creates new form ListarProjetosView
     */
    public CriarNovoProjetoView() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloProjetos = new javax.swing.JLabel();
        btnSalvarProjeto = new javax.swing.JButton();
        inputEmailAtor3 = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        selectTipoProjeto = new javax.swing.JComboBox<>();
        labelEquipe = new javax.swing.JLabel();
        inputNomeProjeto1 = new javax.swing.JTextField();
        inputEmailAtor1 = new javax.swing.JTextField();
        inputEmailAtor4 = new javax.swing.JTextField();
        inputEmailAtor2 = new javax.swing.JTextField();
        inputEmailAtor5 = new javax.swing.JTextField();
        inputEmailAtor6 = new javax.swing.JTextField();
        labelFuncaoAtor = new javax.swing.JLabel();
        selectFuncaoAtor1 = new javax.swing.JComboBox<>();
        selectFuncaoAtor2 = new javax.swing.JComboBox<>();
        selectFuncaoAtor5 = new javax.swing.JComboBox<>();
        selectFuncaoAtor3 = new javax.swing.JComboBox<>();
        selectFuncaoAtor4 = new javax.swing.JComboBox<>();
        selectFuncaoAtor6 = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTituloProjetos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTituloProjetos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloProjetos.setText("Criar Novo Projeto");

        btnSalvarProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarProjeto.setText("Próximo");
        btnSalvarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProjetoActionPerformed(evt);
            }
        });

        inputEmailAtor3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor3.setText("arquitetoSoftware@projeto.com");

        labelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTipo.setText("Tipo:");

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNome.setText("Nome:");

        selectTipoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTipoProjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cascata", "Iterativo/Incremental" }));
        selectTipoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoProjetoActionPerformed(evt);
            }
        });

        labelEquipe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEquipe.setText("Equipe:");

        inputNomeProjeto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNomeProjeto1.setText("Sistema de padaria");

        inputEmailAtor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor1.setText("cliente@projeto.com");
        inputEmailAtor1.setToolTipText("");
        inputEmailAtor1.setName(""); // NOI18N
        inputEmailAtor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor1ActionPerformed(evt);
            }
        });

        inputEmailAtor4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor4.setText("liderTecnico@projeto.com");

        inputEmailAtor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor2.setText("desenvolvedor@projeto.com");

        inputEmailAtor5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor5.setText("gerenteProjeto@projeto.com");

        inputEmailAtor6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor6.setText("analistaQualidade@projeto.com");

        labelFuncaoAtor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFuncaoAtor.setText("Função:");

        selectFuncaoAtor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor1ActionPerformed(evt);
            }
        });

        selectFuncaoAtor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor2ActionPerformed(evt);
            }
        });

        selectFuncaoAtor5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor5ActionPerformed(evt);
            }
        });

        selectFuncaoAtor3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor3ActionPerformed(evt);
            }
        });

        selectFuncaoAtor4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor4ActionPerformed(evt);
            }
        });

        selectFuncaoAtor6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor6ActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelEquipe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputNomeProjeto1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(inputEmailAtor4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(inputEmailAtor3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(inputEmailAtor2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(inputEmailAtor5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(inputEmailAtor6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(inputEmailAtor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFuncaoAtor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectFuncaoAtor2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectFuncaoAtor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectFuncaoAtor3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectFuncaoAtor4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectFuncaoAtor5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectFuncaoAtor6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectTipoProjeto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvarProjeto)))
                .addGap(50, 50, 50))
            .addComponent(txtTituloProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(txtTituloProjetos)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNomeProjeto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTipo)
                    .addComponent(selectTipoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEquipe)
                    .addComponent(inputEmailAtor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFuncaoAtor)
                    .addComponent(selectFuncaoAtor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmailAtor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFuncaoAtor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmailAtor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFuncaoAtor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmailAtor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFuncaoAtor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmailAtor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFuncaoAtor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEmailAtor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFuncaoAtor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarProjeto)
                    .addComponent(btnCancelar))
                .addGap(21, 21, 21))
        );

        inputEmailAtor1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTipoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipoProjetoActionPerformed

    private void selectFuncaoAtor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor1ActionPerformed

    private void selectFuncaoAtor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor2ActionPerformed

    private void selectFuncaoAtor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor5ActionPerformed

    private void selectFuncaoAtor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor3ActionPerformed

    private void selectFuncaoAtor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor4ActionPerformed

    private void selectFuncaoAtor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor6ActionPerformed

    private void btnSalvarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProjetoActionPerformed
        dispose();
        SelecionarModeloQuestionarioView selecionarModeloQuestionarioView = new SelecionarModeloQuestionarioView();
        selecionarModeloQuestionarioView.setVisible(true);
    }//GEN-LAST:event_btnSalvarProjetoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void inputEmailAtor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarNovoProjetoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarProjeto;
    private javax.swing.JTextField inputEmailAtor1;
    private javax.swing.JTextField inputEmailAtor2;
    private javax.swing.JTextField inputEmailAtor3;
    private javax.swing.JTextField inputEmailAtor4;
    private javax.swing.JTextField inputEmailAtor5;
    private javax.swing.JTextField inputEmailAtor6;
    private javax.swing.JTextField inputNomeProjeto1;
    private javax.swing.JLabel labelEquipe;
    private javax.swing.JLabel labelFuncaoAtor;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JComboBox<String> selectFuncaoAtor1;
    private javax.swing.JComboBox<String> selectFuncaoAtor2;
    private javax.swing.JComboBox<String> selectFuncaoAtor3;
    private javax.swing.JComboBox<String> selectFuncaoAtor4;
    private javax.swing.JComboBox<String> selectFuncaoAtor5;
    private javax.swing.JComboBox<String> selectFuncaoAtor6;
    private javax.swing.JComboBox<String> selectTipoProjeto;
    private javax.swing.JLabel txtTituloProjetos;
    // End of variables declaration//GEN-END:variables
}
