/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestaoqualidadeprojetos.view.gerenciamento;

import com.gestaoqualidadeprojetos.view.projeto.CriarNovaIteracaoView;
import com.gestaoqualidadeprojetos.view.projeto.CriarNovaEtapaView;
import com.gestaoqualidadeprojetos.view.projeto.ListarProjetosAdminView;
import com.gestaoqualidadeprojetos.view.questionario.QuestionarioView;

/**
 *
 * @author Gabriel
 */
public class GerenciarIteracoesProjeto extends javax.swing.JFrame {

    /**
     * Creates new form SelecionarModeloQuestionarioView
     */
    public GerenciarIteracoesProjeto() {
        initComponents();
        setVisible(true);
        setResizable(false);
        this.setLocationRelativeTo(this.getParent());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//clicar no X não fechar o sistema inteiro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abasFasesIteracao = new javax.swing.JTabbedPane();
        projetoIteracao1 = new javax.swing.JPanel();
        iteracao1 = new javax.swing.JScrollPane();
        tableEquipe1 = new javax.swing.JTable();
        projetoIteracao2 = new javax.swing.JPanel();
        iteracao2 = new javax.swing.JScrollPane();
        tableEquipe2 = new javax.swing.JTable();
        projetoIteracao3 = new javax.swing.JPanel();
        iteracao3 = new javax.swing.JScrollPane();
        tableEquipe3 = new javax.swing.JTable();
        projetoIteracao4 = new javax.swing.JPanel();
        iteracao7 = new javax.swing.JScrollPane();
        tableEquipe7 = new javax.swing.JTable();
        btnNovaIteracao = new javax.swing.JButton();
        txtTituloSelecionarModeloQuestionario = new javax.swing.JLabel();
        txtTituloSelecionarModeloQuestionario1 = new javax.swing.JLabel();
        btnAbrirQuestionario = new javax.swing.JButton();
        btnNovaEtapa = new javax.swing.JButton();
        btnAumentarPrazo = new javax.swing.JButton();

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Iterações do Projeto");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Iteração Atual:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Sprint 4");

        abasFasesIteracao.setToolTipText("");
        abasFasesIteracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        abasFasesIteracao.setName("Fases da Iteração"); // NOI18N

        tableEquipe1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableEquipe1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Iniciação", "15/03/2023", "30/03/2023", "25/03/2023", "Respondido"},
                {"02", "Requisitos", "15/03/2023", "30/03/2023", "25/03/2023", "Respondido"},
                {"03", "Projeto", "15/03/2023", "30/03/2023", "25/03/2023", "Respondido"},
                {"04", "Desenvolvimento", "15/03/2023", "30/03/2023", "25/03/2023", "Respondido"},
                {"05", "Teste e Verficação", "15/03/2023", "30/03/2023", "25/03/2023", "Respondido"}
            },
            new String [] {
                "#", "Etapa", "Data Abertura", "Prazo para Resposta", "Data da Resposta", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEquipe1.setRowHeight(26);
        tableEquipe1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableEquipe1.setShowGrid(true);
        tableEquipe1.setSurrendersFocusOnKeystroke(true);
        iteracao1.setViewportView(tableEquipe1);
        if (tableEquipe1.getColumnModel().getColumnCount() > 0) {
            tableEquipe1.getColumnModel().getColumn(0).setMinWidth(50);
            tableEquipe1.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableEquipe1.getColumnModel().getColumn(0).setMaxWidth(50);
            tableEquipe1.getColumnModel().getColumn(1).setMinWidth(300);
            tableEquipe1.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableEquipe1.getColumnModel().getColumn(1).setMaxWidth(350);
        }

        javax.swing.GroupLayout projetoIteracao1Layout = new javax.swing.GroupLayout(projetoIteracao1);
        projetoIteracao1.setLayout(projetoIteracao1Layout);
        projetoIteracao1Layout.setHorizontalGroup(
            projetoIteracao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projetoIteracao1Layout.createSequentialGroup()
                .addComponent(iteracao1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        projetoIteracao1Layout.setVerticalGroup(
            projetoIteracao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iteracao1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        abasFasesIteracao.addTab("Sprint 1", projetoIteracao1);

        tableEquipe2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableEquipe2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Iniciação", "15/04/2023", "30/04/2023", "25/04/2023", "Respondido"},
                {"02", "Requisitos", "15/04/2023", "30/04/2023", "25/04/2023", "Respondido"},
                {"03", "Projeto", "15/04/2023", "30/04/2023", "25/04/2023", "Respondido"},
                {"04", "Desenvolvimento", "15/04/2023", "30/04/2023", "25/04/2023", "Respondido"},
                {"05", "Teste e Verficação", "15/04/2023", "30/04/2023", "25/04/2023", "Respondido"}
            },
            new String [] {
                "#", "Etapa", "Data Abertura", "Prazo para Resposta", "Data da Resposta", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEquipe2.setRowHeight(26);
        tableEquipe2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableEquipe2.setShowGrid(true);
        tableEquipe2.setSurrendersFocusOnKeystroke(true);
        iteracao2.setViewportView(tableEquipe2);
        if (tableEquipe2.getColumnModel().getColumnCount() > 0) {
            tableEquipe2.getColumnModel().getColumn(0).setMinWidth(50);
            tableEquipe2.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableEquipe2.getColumnModel().getColumn(0).setMaxWidth(50);
            tableEquipe2.getColumnModel().getColumn(1).setMinWidth(300);
            tableEquipe2.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableEquipe2.getColumnModel().getColumn(1).setMaxWidth(350);
        }

        javax.swing.GroupLayout projetoIteracao2Layout = new javax.swing.GroupLayout(projetoIteracao2);
        projetoIteracao2.setLayout(projetoIteracao2Layout);
        projetoIteracao2Layout.setHorizontalGroup(
            projetoIteracao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iteracao2, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        projetoIteracao2Layout.setVerticalGroup(
            projetoIteracao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iteracao2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        abasFasesIteracao.addTab("Sprint 2", projetoIteracao2);

        tableEquipe3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableEquipe3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Iniciação", "15/05/2023", "30/05/2023", "25/05/2023", "Respondido"},
                {"02", "Requisitos", "15/05/2023", "30/05/2023", "25/05/2023", "Respondido"},
                {"03", "Projeto", "15/05/2023", "30/05/2023", "25/05/2023", "Respondido"},
                {"04", "Desenvolvimento", "15/05/2023", "30/05/2023", "25/05/2023", "Respondido"},
                {"05", "Teste e Verficação", "15/05/2023", "30/05/2023", "25/05/2023", "Respondido"}
            },
            new String [] {
                "#", "Etapa", "Data Abertura", "Prazo para Resposta", "Data da Resposta", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEquipe3.setRowHeight(26);
        tableEquipe3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableEquipe3.setShowGrid(true);
        tableEquipe3.setSurrendersFocusOnKeystroke(true);
        iteracao3.setViewportView(tableEquipe3);
        if (tableEquipe3.getColumnModel().getColumnCount() > 0) {
            tableEquipe3.getColumnModel().getColumn(0).setMinWidth(50);
            tableEquipe3.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableEquipe3.getColumnModel().getColumn(0).setMaxWidth(50);
            tableEquipe3.getColumnModel().getColumn(1).setMinWidth(300);
            tableEquipe3.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableEquipe3.getColumnModel().getColumn(1).setMaxWidth(350);
        }

        javax.swing.GroupLayout projetoIteracao3Layout = new javax.swing.GroupLayout(projetoIteracao3);
        projetoIteracao3.setLayout(projetoIteracao3Layout);
        projetoIteracao3Layout.setHorizontalGroup(
            projetoIteracao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iteracao3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        projetoIteracao3Layout.setVerticalGroup(
            projetoIteracao3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iteracao3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        abasFasesIteracao.addTab("Sprint 3", projetoIteracao3);

        tableEquipe7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableEquipe7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Iniciação", "15/06/2023", "30/06/2023", null, "Aberto"},
                {"02", "Requisitos", "15/06/2023", "30/06/2023", null, "Aberto"},
                {"03", "Projeto", "15/06/2023", "30/06/2023", null, "Aberto"},
                {"04", "Desenvolvimento", "15/06/2023", "30/06/2023", null, "Aberto"},
                {"05", "Teste e Verficação", "15/06/2023", "30/06/2023", null, "Aberto"}
            },
            new String [] {
                "#", "Etapa", "Data Abertura", "Prazo para Resposta", "Data da Resposta", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEquipe7.setRowHeight(26);
        tableEquipe7.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableEquipe7.setShowGrid(true);
        tableEquipe7.setSurrendersFocusOnKeystroke(true);
        iteracao7.setViewportView(tableEquipe7);
        if (tableEquipe7.getColumnModel().getColumnCount() > 0) {
            tableEquipe7.getColumnModel().getColumn(0).setMinWidth(50);
            tableEquipe7.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableEquipe7.getColumnModel().getColumn(0).setMaxWidth(50);
            tableEquipe7.getColumnModel().getColumn(1).setMinWidth(300);
            tableEquipe7.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableEquipe7.getColumnModel().getColumn(1).setMaxWidth(350);
        }

        javax.swing.GroupLayout projetoIteracao4Layout = new javax.swing.GroupLayout(projetoIteracao4);
        projetoIteracao4.setLayout(projetoIteracao4Layout);
        projetoIteracao4Layout.setHorizontalGroup(
            projetoIteracao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iteracao7, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
        );
        projetoIteracao4Layout.setVerticalGroup(
            projetoIteracao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iteracao7, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        abasFasesIteracao.addTab("Sprint 4", projetoIteracao4);

        btnNovaIteracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovaIteracao.setText("Nova Iteração");
        btnNovaIteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaIteracaoActionPerformed(evt);
            }
        });

        txtTituloSelecionarModeloQuestionario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTituloSelecionarModeloQuestionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloSelecionarModeloQuestionario.setText("Projeto: ");

        txtTituloSelecionarModeloQuestionario1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTituloSelecionarModeloQuestionario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloSelecionarModeloQuestionario1.setText("Sistema de Padaria");

        btnAbrirQuestionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAbrirQuestionario.setText("Abrir Questionário");
        btnAbrirQuestionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirQuestionarioActionPerformed(evt);
            }
        });

        btnNovaEtapa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovaEtapa.setText("Nova Etapa");
        btnNovaEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaEtapaActionPerformed(evt);
            }
        });

        btnAumentarPrazo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAumentarPrazo.setText("Aumentar Prazo");
        btnAumentarPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarPrazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovaIteracao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovaEtapa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAumentarPrazo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAbrirQuestionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVoltar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtTituloSelecionarModeloQuestionario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTituloSelecionarModeloQuestionario1))
                                .addComponent(abasFasesIteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloSelecionarModeloQuestionario)
                    .addComponent(txtTituloSelecionarModeloQuestionario1))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addComponent(abasFasesIteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnNovaIteracao)
                    .addComponent(btnAbrirQuestionario)
                    .addComponent(btnNovaEtapa)
                    .addComponent(btnAumentarPrazo))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        //ListarProjetosAdminView listarProjetosAdminView = new ListarProjetosAdminView();
        //listarProjetosAdminView.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnNovaIteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaIteracaoActionPerformed
        CriarNovaIteracaoView criarNovaIteracaoView = new CriarNovaIteracaoView();
        criarNovaIteracaoView.setVisible(true);
    }//GEN-LAST:event_btnNovaIteracaoActionPerformed

    private void btnAbrirQuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirQuestionarioActionPerformed
        GerenciarEtapasIteracao listarPerguntasEtapaIteracaoProjetoView = new GerenciarEtapasIteracao();
        listarPerguntasEtapaIteracaoProjetoView.setVisible(true);
    }//GEN-LAST:event_btnAbrirQuestionarioActionPerformed

    private void btnNovaEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaEtapaActionPerformed
        CriarNovaEtapaView criarNovaEtapaView = new CriarNovaEtapaView();
        criarNovaEtapaView.setVisible(true);
    }//GEN-LAST:event_btnNovaEtapaActionPerformed

    private void btnAumentarPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarPrazoActionPerformed
        AumentarPrazoQuestionárioView aumentarPrazoQuestionárioView = new AumentarPrazoQuestionárioView();
        aumentarPrazoQuestionárioView.setVisible(true);
    }//GEN-LAST:event_btnAumentarPrazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarIteracoesProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarIteracoesProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarIteracoesProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarIteracoesProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarIteracoesProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasFasesIteracao;
    private javax.swing.JButton btnAbrirQuestionario;
    private javax.swing.JButton btnAumentarPrazo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovaEtapa;
    private javax.swing.JButton btnNovaIteracao;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane iteracao1;
    private javax.swing.JScrollPane iteracao2;
    private javax.swing.JScrollPane iteracao3;
    private javax.swing.JScrollPane iteracao7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel projetoIteracao1;
    private javax.swing.JPanel projetoIteracao2;
    private javax.swing.JPanel projetoIteracao3;
    private javax.swing.JPanel projetoIteracao4;
    private javax.swing.JTable tableEquipe1;
    private javax.swing.JTable tableEquipe2;
    private javax.swing.JTable tableEquipe3;
    private javax.swing.JTable tableEquipe7;
    private javax.swing.JLabel txtTituloSelecionarModeloQuestionario;
    private javax.swing.JLabel txtTituloSelecionarModeloQuestionario1;
    // End of variables declaration//GEN-END:variables
}
