/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestaoqualidadeprojetos.view.gerenciamento;

import com.gestaoqualidadeprojetos.view.gerenciamento.GerenciarEtapasIteracao;
import com.gestaoqualidadeprojetos.view.gerenciamento.CriarNovaPerguntaView;

/**
 *
 * @author Gabriel
 */
public class ManterPerguntasEtapaProjetoAbas extends javax.swing.JFrame {

    /**
     * Creates new form PerguntasQuestionarioView
     */
    public ManterPerguntasEtapaProjetoAbas() {
        initComponents();
        setVisible(true);
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//clicar no X não fechar o sistema inteiro
       this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloPerguntasQuestionario = new javax.swing.JLabel();
        btnNovaPergunta = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        txtStatusQuestionario = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        abasMembrosEquipe = new javax.swing.JTabbedPane();
        cliente = new javax.swing.JPanel();
        perguntasFaseAtualDesenvolvedor1 = new javax.swing.JScrollPane();
        tablePerguntasFaseAtualDesenvolvedor1 = new javax.swing.JTable();
        desenvolvedor = new javax.swing.JPanel();
        perguntasFaseAtualDesenvolvedor = new javax.swing.JScrollPane();
        tablePerguntasFaseAtualDesenvolvedor = new javax.swing.JTable();
        arquitetoSoftware = new javax.swing.JPanel();
        perguntasFaseAtualDesenvolvedor2 = new javax.swing.JScrollPane();
        tablePerguntasFaseAtualDesenvolvedor2 = new javax.swing.JTable();
        gerenteProjeto = new javax.swing.JPanel();
        perguntasFaseAtualDesenvolvedor3 = new javax.swing.JScrollPane();
        tablePerguntasFaseAtualDesenvolvedor3 = new javax.swing.JTable();
        liderTecnico = new javax.swing.JPanel();
        perguntasFaseAtualDesenvolvedor4 = new javax.swing.JScrollPane();
        tablePerguntasFaseAtualDesenvolvedor4 = new javax.swing.JTable();
        analistaQualidadee = new javax.swing.JPanel();
        perguntasFaseAtualDesenvolvedor5 = new javax.swing.JScrollPane();
        tablePerguntasFaseAtualDesenvolvedor5 = new javax.swing.JTable();
        txtTituloPerguntasQuestionario1 = new javax.swing.JLabel();
        btnEditarPergunta = new javax.swing.JButton();
        btnNovaPergunta2 = new javax.swing.JButton();
        menuAcoesPerguntasQuestionario = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manter Perguntas da Etapa");

        txtTituloPerguntasQuestionario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTituloPerguntasQuestionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTituloPerguntasQuestionario.setText("Perguntas da Etapa:");

        btnNovaPergunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovaPergunta.setText("Nova pergunta");
        btnNovaPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPerguntaActionPerformed(evt);
            }
        });

        labelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelStatus.setText("Status:");

        txtStatusQuestionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStatusQuestionario.setText("Rascunho");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        abasMembrosEquipe.setToolTipText("");
        abasMembrosEquipe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        abasMembrosEquipe.setName("Fases da Iteração"); // NOI18N

        tablePerguntasFaseAtualDesenvolvedor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePerguntasFaseAtualDesenvolvedor1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Você entendeu os objetivos do software?"},
                {"02", "Você está disposto a fornecer feedback para a equipe de desenvolvimento durante todo o processo?"},
                {"03", "Foi determinado quem toma as decisões em nome da sua empresa?"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Pergunta"
            }
        ));
        tablePerguntasFaseAtualDesenvolvedor1.setRowHeight(26);
        tablePerguntasFaseAtualDesenvolvedor1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePerguntasFaseAtualDesenvolvedor1.setShowGrid(true);
        tablePerguntasFaseAtualDesenvolvedor1.setSurrendersFocusOnKeystroke(true);
        perguntasFaseAtualDesenvolvedor1.setViewportView(tablePerguntasFaseAtualDesenvolvedor1);
        if (tablePerguntasFaseAtualDesenvolvedor1.getColumnModel().getColumnCount() > 0) {
            tablePerguntasFaseAtualDesenvolvedor1.getColumnModel().getColumn(0).setMinWidth(50);
            tablePerguntasFaseAtualDesenvolvedor1.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePerguntasFaseAtualDesenvolvedor1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout clienteLayout = new javax.swing.GroupLayout(cliente);
        cliente.setLayout(clienteLayout);
        clienteLayout.setHorizontalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clienteLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addContainerGap())
        );
        clienteLayout.setVerticalGroup(
            clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abasMembrosEquipe.addTab("Cliente", cliente);

        tablePerguntasFaseAtualDesenvolvedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePerguntasFaseAtualDesenvolvedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Você entendeu os objetivos do software?"},
                {"02", "Você está disposto a fornecer feedback para a equipe de desenvolvimento durante todo o processo?"},
                {"03", "Foi determinado quem toma as decisões em nome da sua empresa?"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Pergunta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePerguntasFaseAtualDesenvolvedor.setRowHeight(26);
        tablePerguntasFaseAtualDesenvolvedor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePerguntasFaseAtualDesenvolvedor.setShowGrid(true);
        tablePerguntasFaseAtualDesenvolvedor.setSurrendersFocusOnKeystroke(true);
        perguntasFaseAtualDesenvolvedor.setViewportView(tablePerguntasFaseAtualDesenvolvedor);
        if (tablePerguntasFaseAtualDesenvolvedor.getColumnModel().getColumnCount() > 0) {
            tablePerguntasFaseAtualDesenvolvedor.getColumnModel().getColumn(0).setMinWidth(50);
            tablePerguntasFaseAtualDesenvolvedor.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePerguntasFaseAtualDesenvolvedor.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout desenvolvedorLayout = new javax.swing.GroupLayout(desenvolvedor);
        desenvolvedor.setLayout(desenvolvedorLayout);
        desenvolvedorLayout.setHorizontalGroup(
            desenvolvedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desenvolvedorLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addContainerGap())
        );
        desenvolvedorLayout.setVerticalGroup(
            desenvolvedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desenvolvedorLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abasMembrosEquipe.addTab("Desenvolvedor", desenvolvedor);

        tablePerguntasFaseAtualDesenvolvedor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePerguntasFaseAtualDesenvolvedor2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Você entendeu os objetivos do software?"},
                {"02", "Você está disposto a fornecer feedback para a equipe de desenvolvimento durante todo o processo?"},
                {"03", "Foi determinado quem toma as decisões em nome da sua empresa?"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Pergunta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePerguntasFaseAtualDesenvolvedor2.setRowHeight(26);
        tablePerguntasFaseAtualDesenvolvedor2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePerguntasFaseAtualDesenvolvedor2.setShowGrid(true);
        tablePerguntasFaseAtualDesenvolvedor2.setSurrendersFocusOnKeystroke(true);
        perguntasFaseAtualDesenvolvedor2.setViewportView(tablePerguntasFaseAtualDesenvolvedor2);
        if (tablePerguntasFaseAtualDesenvolvedor2.getColumnModel().getColumnCount() > 0) {
            tablePerguntasFaseAtualDesenvolvedor2.getColumnModel().getColumn(0).setMinWidth(50);
            tablePerguntasFaseAtualDesenvolvedor2.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePerguntasFaseAtualDesenvolvedor2.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout arquitetoSoftwareLayout = new javax.swing.GroupLayout(arquitetoSoftware);
        arquitetoSoftware.setLayout(arquitetoSoftwareLayout);
        arquitetoSoftwareLayout.setHorizontalGroup(
            arquitetoSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, arquitetoSoftwareLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor2, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addContainerGap())
        );
        arquitetoSoftwareLayout.setVerticalGroup(
            arquitetoSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arquitetoSoftwareLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abasMembrosEquipe.addTab("Arquiteto de Software", arquitetoSoftware);

        tablePerguntasFaseAtualDesenvolvedor3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePerguntasFaseAtualDesenvolvedor3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Você entendeu os objetivos do software?"},
                {"02", "Você está disposto a fornecer feedback para a equipe de desenvolvimento durante todo o processo?"},
                {"03", "Foi determinado quem toma as decisões em nome da sua empresa?"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Pergunta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePerguntasFaseAtualDesenvolvedor3.setRowHeight(26);
        tablePerguntasFaseAtualDesenvolvedor3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePerguntasFaseAtualDesenvolvedor3.setShowGrid(true);
        tablePerguntasFaseAtualDesenvolvedor3.setSurrendersFocusOnKeystroke(true);
        perguntasFaseAtualDesenvolvedor3.setViewportView(tablePerguntasFaseAtualDesenvolvedor3);
        if (tablePerguntasFaseAtualDesenvolvedor3.getColumnModel().getColumnCount() > 0) {
            tablePerguntasFaseAtualDesenvolvedor3.getColumnModel().getColumn(0).setMinWidth(50);
            tablePerguntasFaseAtualDesenvolvedor3.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePerguntasFaseAtualDesenvolvedor3.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout gerenteProjetoLayout = new javax.swing.GroupLayout(gerenteProjeto);
        gerenteProjeto.setLayout(gerenteProjetoLayout);
        gerenteProjetoLayout.setHorizontalGroup(
            gerenteProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gerenteProjetoLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor3, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addContainerGap())
        );
        gerenteProjetoLayout.setVerticalGroup(
            gerenteProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerenteProjetoLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abasMembrosEquipe.addTab("Gerente de Projeto", gerenteProjeto);

        tablePerguntasFaseAtualDesenvolvedor4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePerguntasFaseAtualDesenvolvedor4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Você entendeu os objetivos do software?"},
                {"02", "Você está disposto a fornecer feedback para a equipe de desenvolvimento durante todo o processo?"},
                {"03", "Foi determinado quem toma as decisões em nome da sua empresa?"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Pergunta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePerguntasFaseAtualDesenvolvedor4.setRowHeight(26);
        tablePerguntasFaseAtualDesenvolvedor4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePerguntasFaseAtualDesenvolvedor4.setShowGrid(true);
        tablePerguntasFaseAtualDesenvolvedor4.setSurrendersFocusOnKeystroke(true);
        perguntasFaseAtualDesenvolvedor4.setViewportView(tablePerguntasFaseAtualDesenvolvedor4);
        if (tablePerguntasFaseAtualDesenvolvedor4.getColumnModel().getColumnCount() > 0) {
            tablePerguntasFaseAtualDesenvolvedor4.getColumnModel().getColumn(0).setMinWidth(50);
            tablePerguntasFaseAtualDesenvolvedor4.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePerguntasFaseAtualDesenvolvedor4.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout liderTecnicoLayout = new javax.swing.GroupLayout(liderTecnico);
        liderTecnico.setLayout(liderTecnicoLayout);
        liderTecnicoLayout.setHorizontalGroup(
            liderTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, liderTecnicoLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor4, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addContainerGap())
        );
        liderTecnicoLayout.setVerticalGroup(
            liderTecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liderTecnicoLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abasMembrosEquipe.addTab("Líder Técnico", liderTecnico);

        tablePerguntasFaseAtualDesenvolvedor5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePerguntasFaseAtualDesenvolvedor5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Você entendeu os objetivos do software?"},
                {"02", "Você está disposto a fornecer feedback para a equipe de desenvolvimento durante todo o processo?"},
                {"03", "Foi determinado quem toma as decisões em nome da sua empresa?"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Pergunta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePerguntasFaseAtualDesenvolvedor5.setRowHeight(26);
        tablePerguntasFaseAtualDesenvolvedor5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePerguntasFaseAtualDesenvolvedor5.setShowGrid(true);
        tablePerguntasFaseAtualDesenvolvedor5.setSurrendersFocusOnKeystroke(true);
        perguntasFaseAtualDesenvolvedor5.setViewportView(tablePerguntasFaseAtualDesenvolvedor5);
        if (tablePerguntasFaseAtualDesenvolvedor5.getColumnModel().getColumnCount() > 0) {
            tablePerguntasFaseAtualDesenvolvedor5.getColumnModel().getColumn(0).setMinWidth(50);
            tablePerguntasFaseAtualDesenvolvedor5.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePerguntasFaseAtualDesenvolvedor5.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout analistaQualidadeeLayout = new javax.swing.GroupLayout(analistaQualidadee);
        analistaQualidadee.setLayout(analistaQualidadeeLayout);
        analistaQualidadeeLayout.setHorizontalGroup(
            analistaQualidadeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analistaQualidadeeLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor5, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                .addContainerGap())
        );
        analistaQualidadeeLayout.setVerticalGroup(
            analistaQualidadeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analistaQualidadeeLayout.createSequentialGroup()
                .addComponent(perguntasFaseAtualDesenvolvedor5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        abasMembrosEquipe.addTab("Analista de Qualidade", analistaQualidadee);

        txtTituloPerguntasQuestionario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTituloPerguntasQuestionario1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTituloPerguntasQuestionario1.setText("Iniciação");

        btnEditarPergunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarPergunta.setText("Editar");
        btnEditarPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerguntaActionPerformed(evt);
            }
        });

        btnNovaPergunta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovaPergunta2.setText("Excluir");
        btnNovaPergunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPergunta2ActionPerformed(evt);
            }
        });
        setJMenuBar(menuAcoesPerguntasQuestionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abasMembrosEquipe)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelStatus)
                        .addGap(12, 12, 12)
                        .addComponent(txtStatusQuestionario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovaPergunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarPergunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovaPergunta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtTituloPerguntasQuestionario, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtTituloPerguntasQuestionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloPerguntasQuestionario)
                    .addComponent(txtTituloPerguntasQuestionario1))
                .addGap(35, 35, 35)
                .addComponent(abasMembrosEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(txtStatusQuestionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovaPergunta)
                        .addComponent(btnEditarPergunta)
                        .addComponent(btnNovaPergunta2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar1)
                        .addComponent(btnCancelar)))
                .addGap(20, 20, 20))
        );

        abasMembrosEquipe.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPerguntaActionPerformed
        CriarNovaPerguntaView criarNovaPerguntaView = new CriarNovaPerguntaView();
        criarNovaPerguntaView.setVisible(true);
    }//GEN-LAST:event_btnNovaPerguntaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnEditarPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerguntaActionPerformed
        EditarPerguntaView editarPerguntaView = new EditarPerguntaView();
        editarPerguntaView.setVisible(true);
    }//GEN-LAST:event_btnEditarPerguntaActionPerformed

    private void btnNovaPergunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPergunta2ActionPerformed
        
    }//GEN-LAST:event_btnNovaPergunta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoAbas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterPerguntasEtapaProjetoAbas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasMembrosEquipe;
    private javax.swing.JPanel analistaQualidadee;
    private javax.swing.JPanel arquitetoSoftware;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarPergunta;
    private javax.swing.JButton btnNovaPergunta;
    private javax.swing.JButton btnNovaPergunta2;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JPanel cliente;
    private javax.swing.JPanel desenvolvedor;
    private javax.swing.JPanel gerenteProjeto;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel liderTecnico;
    private javax.swing.JMenuBar menuAcoesPerguntasQuestionario;
    private javax.swing.JScrollPane perguntasFaseAtualDesenvolvedor;
    private javax.swing.JScrollPane perguntasFaseAtualDesenvolvedor1;
    private javax.swing.JScrollPane perguntasFaseAtualDesenvolvedor2;
    private javax.swing.JScrollPane perguntasFaseAtualDesenvolvedor3;
    private javax.swing.JScrollPane perguntasFaseAtualDesenvolvedor4;
    private javax.swing.JScrollPane perguntasFaseAtualDesenvolvedor5;
    private javax.swing.JTable tablePerguntasFaseAtualDesenvolvedor;
    private javax.swing.JTable tablePerguntasFaseAtualDesenvolvedor1;
    private javax.swing.JTable tablePerguntasFaseAtualDesenvolvedor2;
    private javax.swing.JTable tablePerguntasFaseAtualDesenvolvedor3;
    private javax.swing.JTable tablePerguntasFaseAtualDesenvolvedor4;
    private javax.swing.JTable tablePerguntasFaseAtualDesenvolvedor5;
    private javax.swing.JLabel txtStatusQuestionario;
    private javax.swing.JLabel txtTituloPerguntasQuestionario;
    private javax.swing.JLabel txtTituloPerguntasQuestionario1;
    // End of variables declaration//GEN-END:variables
}
