/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestaoqualidadeprojetos.view.gerenciamento;

import com.gestaoqualidadeprojetos.view.gerenciamento.GerenciarEtapasIteracao;
import com.gestaoqualidadeprojetos.view.gerenciamento.CriarNovaPerguntaView;

/**
 *
 * @author Gabriel
 */
public class ManterPerguntasEtapaProjetoView extends javax.swing.JFrame {

    /**
     * Creates new form PerguntasQuestionarioView
     */
    public ManterPerguntasEtapaProjetoView() {
        initComponents();
        setVisible(true);
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//clicar no X não fechar o sistema inteiro
       this.setLocationRelativeTo(this.getParent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloPerguntasQuestionario = new javax.swing.JLabel();
        btnNovaPergunta = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        txtStatusQuestionario = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        txtTituloPerguntasQuestionario1 = new javax.swing.JLabel();
        btnEditarPergunta = new javax.swing.JButton();
        btnNovaPergunta2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        perguntasFaseAtualDesenvolvedor6 = new javax.swing.JScrollPane();
        tablePerguntasFaseAtualDesenvolvedor6 = new javax.swing.JTable();
        txtTituloPerguntasQuestionario2 = new javax.swing.JLabel();
        menuAcoesPerguntasQuestionario = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manter Perguntas da Etapa");

        txtTituloPerguntasQuestionario.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTituloPerguntasQuestionario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTituloPerguntasQuestionario.setText("Perguntas da Etapa:");

        btnNovaPergunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovaPergunta.setText("Nova pergunta");
        btnNovaPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPerguntaActionPerformed(evt);
            }
        });

        labelStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelStatus.setText("Status:");

        txtStatusQuestionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStatusQuestionario.setText("Rascunho");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        txtTituloPerguntasQuestionario1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTituloPerguntasQuestionario1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTituloPerguntasQuestionario1.setText("Iniciação");

        btnEditarPergunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarPergunta.setText("Editar");
        btnEditarPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerguntaActionPerformed(evt);
            }
        });

        btnNovaPergunta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovaPergunta2.setText("Excluir");
        btnNovaPergunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPergunta2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Participante:");

        tablePerguntasFaseAtualDesenvolvedor6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePerguntasFaseAtualDesenvolvedor6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Você entendeu os objetivos do software?"},
                {"02", "Você está disposto a fornecer feedback para a equipe de desenvolvimento durante todo o processo?"},
                {"03", "Foi determinado quem toma as decisões em nome da sua empresa?"},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "#", "Pergunta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePerguntasFaseAtualDesenvolvedor6.setRowHeight(26);
        tablePerguntasFaseAtualDesenvolvedor6.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePerguntasFaseAtualDesenvolvedor6.setShowGrid(true);
        tablePerguntasFaseAtualDesenvolvedor6.setSurrendersFocusOnKeystroke(true);
        perguntasFaseAtualDesenvolvedor6.setViewportView(tablePerguntasFaseAtualDesenvolvedor6);
        if (tablePerguntasFaseAtualDesenvolvedor6.getColumnModel().getColumnCount() > 0) {
            tablePerguntasFaseAtualDesenvolvedor6.getColumnModel().getColumn(0).setMinWidth(50);
            tablePerguntasFaseAtualDesenvolvedor6.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePerguntasFaseAtualDesenvolvedor6.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        txtTituloPerguntasQuestionario2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTituloPerguntasQuestionario2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTituloPerguntasQuestionario2.setText("Cliente");
        setJMenuBar(menuAcoesPerguntasQuestionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelStatus)
                                .addGap(12, 12, 12)
                                .addComponent(txtStatusQuestionario))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNovaPergunta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditarPergunta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNovaPergunta2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                                .addComponent(btnSalvar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(perguntasFaseAtualDesenvolvedor6, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTituloPerguntasQuestionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTituloPerguntasQuestionario1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTituloPerguntasQuestionario2)))
                        .addContainerGap(778, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloPerguntasQuestionario)
                    .addComponent(txtTituloPerguntasQuestionario1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTituloPerguntasQuestionario2))
                .addGap(23, 23, 23)
                .addComponent(perguntasFaseAtualDesenvolvedor6, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(txtStatusQuestionario))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovaPergunta)
                        .addComponent(btnEditarPergunta)
                        .addComponent(btnNovaPergunta2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar1)
                        .addComponent(btnCancelar)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPerguntaActionPerformed
        CriarNovaPerguntaView criarNovaPerguntaView = new CriarNovaPerguntaView();
        criarNovaPerguntaView.setVisible(true);
    }//GEN-LAST:event_btnNovaPerguntaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        dispose();
        GerenciarEtapasIteracao listarPerguntasEtapaIteracaoProjetoView = new GerenciarEtapasIteracao();
        listarPerguntasEtapaIteracaoProjetoView.setVisible(true);
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void btnEditarPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerguntaActionPerformed
        EditarPerguntaView editarPerguntaView = new EditarPerguntaView();
        editarPerguntaView.setVisible(true);
    }//GEN-LAST:event_btnEditarPerguntaActionPerformed

    private void btnNovaPergunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPergunta2ActionPerformed
        
    }//GEN-LAST:event_btnNovaPergunta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterPerguntasEtapaProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterPerguntasEtapaProjetoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditarPergunta;
    private javax.swing.JButton btnNovaPergunta;
    private javax.swing.JButton btnNovaPergunta2;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JMenuBar menuAcoesPerguntasQuestionario;
    private javax.swing.JScrollPane perguntasFaseAtualDesenvolvedor6;
    private javax.swing.JTable tablePerguntasFaseAtualDesenvolvedor6;
    private javax.swing.JLabel txtStatusQuestionario;
    private javax.swing.JLabel txtTituloPerguntasQuestionario;
    private javax.swing.JLabel txtTituloPerguntasQuestionario1;
    private javax.swing.JLabel txtTituloPerguntasQuestionario2;
    // End of variables declaration//GEN-END:variables
}
