/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gestaoqualidadeprojetos.view.projeto;

import com.gestaoqualidadeprojetos.view.gerenciamento.GerenciarIteracoesProjeto;
import com.gestaoqualidadeprojetos.view.projeto.ListarProjetosAdminView;
import javax.swing.JFrame;

/**
 *
 * @author Gabriel
 */
public class CriarNovoProjetoView extends javax.swing.JFrame {

    /**
     * Creates new form ListarProjetosView
     */
    public CriarNovoProjetoView() {
        initComponents();
        setVisible(true);
        setResizable(false);
        this.setLocationRelativeTo(this.getParent());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//clicar no X não fechar o sistema inteiro
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloProjetos = new javax.swing.JLabel();
        btnSalvarProjeto = new javax.swing.JButton();
        inputEmailAtor3 = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        selectTipoProjeto = new javax.swing.JComboBox<>();
        labelEquipe = new javax.swing.JLabel();
        inputNomeProjeto1 = new javax.swing.JTextField();
        inputEmailAtor1 = new javax.swing.JTextField();
        inputEmailAtor4 = new javax.swing.JTextField();
        inputEmailAtor2 = new javax.swing.JTextField();
        inputEmailAtor5 = new javax.swing.JTextField();
        inputEmailAtor6 = new javax.swing.JTextField();
        labelFuncaoAtor = new javax.swing.JLabel();
        selectFuncaoAtor1 = new javax.swing.JComboBox<>();
        selectFuncaoAtor2 = new javax.swing.JComboBox<>();
        selectFuncaoAtor5 = new javax.swing.JComboBox<>();
        selectFuncaoAtor3 = new javax.swing.JComboBox<>();
        selectFuncaoAtor4 = new javax.swing.JComboBox<>();
        selectFuncaoAtor6 = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        inputEmailAtor7 = new javax.swing.JTextField();
        inputEmailAtor8 = new javax.swing.JTextField();
        inputEmailAtor9 = new javax.swing.JTextField();
        inputEmailAtor10 = new javax.swing.JTextField();
        inputEmailAtor11 = new javax.swing.JTextField();
        inputEmailAtor12 = new javax.swing.JTextField();
        inputEmailAtor13 = new javax.swing.JTextField();
        inputEmailAtor14 = new javax.swing.JTextField();
        inputEmailAtor15 = new javax.swing.JTextField();
        inputEmailAtor16 = new javax.swing.JTextField();
        inputEmailAtor17 = new javax.swing.JTextField();
        inputEmailAtor18 = new javax.swing.JTextField();
        labelQuestionario = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criar Novo Projeto");

        txtTituloProjetos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtTituloProjetos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloProjetos.setText("Preencha os dados do novo Projeto");

        btnSalvarProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarProjeto.setText("Próximo");
        btnSalvarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProjetoActionPerformed(evt);
            }
        });

        inputEmailAtor3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor3.setText("arquitetoSoftware@projeto.com");

        labelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTipo.setText("Tipo de Projeto:");

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNome.setText("Nome:");

        selectTipoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTipoProjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cascata", "Iterativo/Incremental" }));
        selectTipoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoProjetoActionPerformed(evt);
            }
        });

        labelEquipe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEquipe.setText("Equipe:");

        inputNomeProjeto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNomeProjeto1.setText("Sistema de padaria");

        inputEmailAtor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor1.setText("cliente@projeto.com");
        inputEmailAtor1.setToolTipText("");
        inputEmailAtor1.setName(""); // NOI18N
        inputEmailAtor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor1ActionPerformed(evt);
            }
        });

        inputEmailAtor4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor4.setText("liderTecnico@projeto.com");

        inputEmailAtor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor2.setText("desenvolvedor@projeto.com");

        inputEmailAtor5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor5.setText("gerenteProjeto@projeto.com");

        inputEmailAtor6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor6.setText("analistaQualidade@projeto.com");

        labelFuncaoAtor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelFuncaoAtor.setText("Função:");

        selectFuncaoAtor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor1ActionPerformed(evt);
            }
        });

        selectFuncaoAtor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor2ActionPerformed(evt);
            }
        });

        selectFuncaoAtor5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor5ActionPerformed(evt);
            }
        });

        selectFuncaoAtor3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor3ActionPerformed(evt);
            }
        });

        selectFuncaoAtor4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor4ActionPerformed(evt);
            }
        });

        selectFuncaoAtor6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectFuncaoAtor6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Desenvolvedor", "Arquiteto de Software", "Líder Técnico", "Gerente de Projeto", "Analista de Qualidade" }));
        selectFuncaoAtor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFuncaoAtor6ActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        inputEmailAtor7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor7.setText("Fulano");
        inputEmailAtor7.setToolTipText("");
        inputEmailAtor7.setName(""); // NOI18N
        inputEmailAtor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor7ActionPerformed(evt);
            }
        });

        inputEmailAtor8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor8.setText("de Tal");
        inputEmailAtor8.setToolTipText("");
        inputEmailAtor8.setName(""); // NOI18N
        inputEmailAtor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor8ActionPerformed(evt);
            }
        });

        inputEmailAtor9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor9.setText("Fulano");
        inputEmailAtor9.setToolTipText("");
        inputEmailAtor9.setName(""); // NOI18N
        inputEmailAtor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor9ActionPerformed(evt);
            }
        });

        inputEmailAtor10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor10.setText("de Tal");
        inputEmailAtor10.setToolTipText("");
        inputEmailAtor10.setName(""); // NOI18N
        inputEmailAtor10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor10ActionPerformed(evt);
            }
        });

        inputEmailAtor11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor11.setText("Fulano");
        inputEmailAtor11.setToolTipText("");
        inputEmailAtor11.setName(""); // NOI18N
        inputEmailAtor11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor11ActionPerformed(evt);
            }
        });

        inputEmailAtor12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor12.setText("de Tal");
        inputEmailAtor12.setToolTipText("");
        inputEmailAtor12.setName(""); // NOI18N
        inputEmailAtor12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor12ActionPerformed(evt);
            }
        });

        inputEmailAtor13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor13.setText("Fulano");
        inputEmailAtor13.setToolTipText("");
        inputEmailAtor13.setName(""); // NOI18N
        inputEmailAtor13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor13ActionPerformed(evt);
            }
        });

        inputEmailAtor14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor14.setText("de Tal");
        inputEmailAtor14.setToolTipText("");
        inputEmailAtor14.setName(""); // NOI18N
        inputEmailAtor14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor14ActionPerformed(evt);
            }
        });

        inputEmailAtor15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor15.setText("Fulano");
        inputEmailAtor15.setToolTipText("");
        inputEmailAtor15.setName(""); // NOI18N
        inputEmailAtor15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor15ActionPerformed(evt);
            }
        });

        inputEmailAtor16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor16.setText("de Tal");
        inputEmailAtor16.setToolTipText("");
        inputEmailAtor16.setName(""); // NOI18N
        inputEmailAtor16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor16ActionPerformed(evt);
            }
        });

        inputEmailAtor17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor17.setText("Fulano");
        inputEmailAtor17.setToolTipText("");
        inputEmailAtor17.setName(""); // NOI18N
        inputEmailAtor17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor17ActionPerformed(evt);
            }
        });

        inputEmailAtor18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailAtor18.setText("de Tal");
        inputEmailAtor18.setToolTipText("");
        inputEmailAtor18.setName(""); // NOI18N
        inputEmailAtor18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailAtor18ActionPerformed(evt);
            }
        });

        labelQuestionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelQuestionario.setText("Selecione o Questionário Modelo:");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padrão", "Sistema de padaria", "App para academia", "Rede social", "Importar Questionário" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTituloProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvarProjeto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelEquipe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(inputEmailAtor15, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(inputEmailAtor16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(inputEmailAtor13)
                                                .addGap(18, 18, 18)
                                                .addComponent(inputEmailAtor14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(inputEmailAtor11)
                                                .addGap(18, 18, 18)
                                                .addComponent(inputEmailAtor12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(inputEmailAtor7, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(inputEmailAtor9))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(inputEmailAtor10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(inputEmailAtor8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputEmailAtor17)
                                                .addGap(18, 18, 18)
                                                .addComponent(inputEmailAtor18, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputEmailAtor5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputEmailAtor4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputEmailAtor3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputEmailAtor2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputEmailAtor1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(inputEmailAtor6, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelFuncaoAtor)
                                        .addGap(65, 65, 65))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(selectFuncaoAtor6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectFuncaoAtor5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectFuncaoAtor4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectFuncaoAtor3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectFuncaoAtor2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectFuncaoAtor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelQuestionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputNomeProjeto1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectTipoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(739, 739, 739))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtTituloProjetos)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNomeProjeto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEquipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputEmailAtor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEmailAtor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputEmailAtor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEmailAtor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputEmailAtor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEmailAtor12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputEmailAtor13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEmailAtor14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputEmailAtor15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEmailAtor16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputEmailAtor17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputEmailAtor18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputEmailAtor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEmailAtor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEmailAtor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(inputEmailAtor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEmailAtor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEmailAtor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFuncaoAtor)
                        .addGap(12, 12, 12)
                        .addComponent(selectFuncaoAtor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFuncaoAtor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFuncaoAtor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(selectFuncaoAtor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFuncaoAtor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectFuncaoAtor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(selectTipoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuestionario)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarProjeto)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25))
        );

        inputEmailAtor1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectTipoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipoProjetoActionPerformed

    private void selectFuncaoAtor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor1ActionPerformed

    private void selectFuncaoAtor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor2ActionPerformed

    private void selectFuncaoAtor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor5ActionPerformed

    private void selectFuncaoAtor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor3ActionPerformed

    private void selectFuncaoAtor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor4ActionPerformed

    private void selectFuncaoAtor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFuncaoAtor6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFuncaoAtor6ActionPerformed

    private void btnSalvarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProjetoActionPerformed
        this.dispose();
        GerenciarIteracoesProjeto gerenciarIteracoesProjeto = new GerenciarIteracoesProjeto();
        gerenciarIteracoesProjeto.setVisible(true);
    }//GEN-LAST:event_btnSalvarProjetoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        ListarProjetosAdminView listarProjetosAdminView = new ListarProjetosAdminView();
        listarProjetosAdminView.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void inputEmailAtor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor1ActionPerformed

    private void inputEmailAtor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor7ActionPerformed

    private void inputEmailAtor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor8ActionPerformed

    private void inputEmailAtor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor9ActionPerformed

    private void inputEmailAtor10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor10ActionPerformed

    private void inputEmailAtor11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor11ActionPerformed

    private void inputEmailAtor12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor12ActionPerformed

    private void inputEmailAtor13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor13ActionPerformed

    private void inputEmailAtor14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor14ActionPerformed

    private void inputEmailAtor15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor15ActionPerformed

    private void inputEmailAtor16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor16ActionPerformed

    private void inputEmailAtor17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor17ActionPerformed

    private void inputEmailAtor18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailAtor18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailAtor18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarNovoProjetoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarNovoProjetoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarProjeto;
    private javax.swing.JTextField inputEmailAtor1;
    private javax.swing.JTextField inputEmailAtor10;
    private javax.swing.JTextField inputEmailAtor11;
    private javax.swing.JTextField inputEmailAtor12;
    private javax.swing.JTextField inputEmailAtor13;
    private javax.swing.JTextField inputEmailAtor14;
    private javax.swing.JTextField inputEmailAtor15;
    private javax.swing.JTextField inputEmailAtor16;
    private javax.swing.JTextField inputEmailAtor17;
    private javax.swing.JTextField inputEmailAtor18;
    private javax.swing.JTextField inputEmailAtor2;
    private javax.swing.JTextField inputEmailAtor3;
    private javax.swing.JTextField inputEmailAtor4;
    private javax.swing.JTextField inputEmailAtor5;
    private javax.swing.JTextField inputEmailAtor6;
    private javax.swing.JTextField inputEmailAtor7;
    private javax.swing.JTextField inputEmailAtor8;
    private javax.swing.JTextField inputEmailAtor9;
    private javax.swing.JTextField inputNomeProjeto1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labelEquipe;
    private javax.swing.JLabel labelFuncaoAtor;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelQuestionario;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JComboBox<String> selectFuncaoAtor1;
    private javax.swing.JComboBox<String> selectFuncaoAtor2;
    private javax.swing.JComboBox<String> selectFuncaoAtor3;
    private javax.swing.JComboBox<String> selectFuncaoAtor4;
    private javax.swing.JComboBox<String> selectFuncaoAtor5;
    private javax.swing.JComboBox<String> selectFuncaoAtor6;
    private javax.swing.JComboBox<String> selectTipoProjeto;
    private javax.swing.JLabel txtTituloProjetos;
    // End of variables declaration//GEN-END:variables
}
